### ISSUE TITLE
Remove include

### ISSUE THREAD

**Issue by PatrickvL** [allkern/psx#2]
The log.h include in msf.c seems not needed and if so should be removed (making it somewhat easier to repurpose in xemu for instance)

**Comment by PatrickvL** [comment]
Referring to https://github.com/xemu-project/xemu/issues/435#issuecomment-2226738051

**Comment by PatrickvL** [comment]
Above applies to master branch

**Comment by PatrickvL** [comment]
In cdrom_rewrite branch, cue.h should probably not include disc.h

Edit: for this, move cue_init_disc() over to disc.c

**Comment by PatrickvL** [comment]
Perhaps the cue reader could be moved to a separate repo, and used here via a git submodule?

**Comment by allkern** [comment]
Sure, I'll be working towards a separate repo, shouldn't take too long

**Comment by allkern** [comment]
> Perhaps the cue reader could be moved to a separate repo, and used here via a git submodule?

Code is up: https://github.com/allkern/cue

**Comment by PatrickvL** [comment]
I guess one of your next commits in the cdrom_rewrite branch will make use of the extracted tiny cue repo?
